/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface OsButton {}
  interface OsButtonAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'OsButton': Components.OsButton;
  }

  interface StencilIntrinsicElements {
    'os-button': Components.OsButtonAttributes;
  }


  interface HTMLOsButtonElement extends Components.OsButton, HTMLStencilElement {}
  var HTMLOsButtonElement: {
    prototype: HTMLOsButtonElement;
    new (): HTMLOsButtonElement;
  };

  interface HTMLElementTagNameMap {
    'os-button': HTMLOsButtonElement
  }

  interface ElementTagNameMap {
    'os-button': HTMLOsButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
